---
scrape_configs:
- job_name: postgres
  scrape_interval: 15s
  static_configs:
  - targets: ["postgres-exporter:9187"]
- job_name: pushgateway
  scrape_interval: 15s
  static_configs:
  - targets: ["prometheus-pushgateway:9091"]
  honor_labels: true